#!/usr/bin/env python3

import os
from bs4 import BeautifulSoup

os.chdir("./docs")

with open("_navbar.html") as file:
    navbar = file.read()
navbarSoup = BeautifulSoup(navbar, 'html.parser')

for file in os.listdir("./"):
    if file.endswith(".html") and not file.startswith("_"):
        with open(file) as file:
            currentFile = file.read()
        currentFileSoup = BeautifulSoup(currentFile, 'html.parser')
        name = currentFileSoup.find(id='name')
        cont = True
        for navbarLiEntry in navbarSoup.find_all(name="li"):
            for navbarEntry in navbarSoup.find_all(name="a"):
                if navbarEntry.get('href') == file.name:
                    cont = False
                if navbarEntry.get('href') not in os.listdir("./"):
                    _ = navbarLiEntry.extract()
        if cont:
            try:
                newTag = BeautifulSoup(f'<li><a href="{file.name}">{name.text}</a></li>', 'html.parser')
                navbarSoup.nav.ul.append(newTag)
            except: continue

with open("_navbar.html", "w") as out:
    out.write(str(navbarSoup))

for file in os.listdir("./"):
    with open("_navbar.html") as openedNavbarFile:
        navbar = openedNavbarFile.read()
    navbarSoup = BeautifulSoup(navbar, 'html.parser')
    if file.endswith(".html") and not file.startswith("_"):
        print("Adding navbar to " + file + "...")
        with open(file) as openedFile:
            currentFile = openedFile.read()
        currentFileSoup = BeautifulSoup(currentFile, 'html.parser')
        for i in currentFileSoup.find_all("nav"):
            _ = i.extract()
        try:
            currentFileSoup.html.insert(0, navbarSoup)
        except:
            print("Could not add navbar to " + file + "...")
            continue
        with open(file, "w") as out:
            out.write(str(currentFileSoup))

os.chdir("../")
print("Compiling stylesheets...")
os.system("./build-stylesheets")
print("Done")
